{% assign upboundLink = "https://upbound.io/" %}
{% assign slackLink = "https://slack.crossplane.io/" %}
{% assign githubLink = "https://github.com/crossplane/crossplane" %}
{% assign twitterLink = "https://twitter.com/crossplane_io" %}
{% assign forumLink = "https://groups.google.com/forum/#!forum/crossplane-dev" %}
{% assign youtubeLink = "https://www.youtube.com/channel/UC19FgzMBMqBro361HbE46Fw" %}
{% assign podcastLink = "https://www.youtube.com/playlist?list=PL510POnNVaaYFuK-B_SIUrpIonCtLVOzT" %}
{% assign blogLink = "https://blog.crossplane.io/" %}
{% assign communityMeetingLink = "https://github.com/crossplane/crossplane/#get-involved" %}
{% assign latestDocs = "/docs/v1.2" | append: '/' | relative_url %}
{% assign cncfLink = "https://www.cncf.io/" %}
