{% assign slackLink = "https://slack.crossplane.io/" %}
{% assign githubLink = "https://github.com/crossplaneio/crossplane" %}
{% assign twitterLink = "https://twitter.com/crossplane_io" %}
{% assign forumLink = "https://groups.google.com/forum/#!forum/crossplane-dev" %}
{% assign youtubeLink = "https://www.youtube.com/channel/UC19FgzMBMqBro361HbE46Fw" %}
{% assign podcastLink = "https://www.youtube.com/playlist?list=PL510POnNVaaYFuK-B_SIUrpIonCtLVOzT" %}
{% assign blogLink = "https://blog.crossplane.io/" %}
{% assign communityMeetingLink = "https://github.com/crossplaneio/crossplane/#community-meeting" %}
{% assign latestDocs = site.data.versions[0].path | append: '/' | relative_url %}
